on:
  push:
    tags: ["v*-prod"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mxdeployer-sample-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet publish -r "win-x64" -c Release --self-contained true -p:PublishSingleFile=true -o ./build

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: mxdeployer-sample-prod.zip
          path: ./build

      - name: Deploy to production
        uses: mxdeployer/mxdeployer-action@v0.4
        with:
          dest-host: "WIN11ANDY-PROD"
          message: "${{ secrets.MESSAGE }}"
