on:
  push:
    tags: ["v*-stage"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mxdeployer-sample-stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet publish -r "win-x64" -c Release --self-contained true -p:PublishSingleFile=true -o ./build

      - name: Show me what you've got!
        run: ls -laF ./build

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: mxdeployer-sample-stage.zip
          path: ./build

      - name: Deploy to stage
        uses: mxdeployer/mxdeployer-action@v0.4
        with:
          dest-host: "WIN11ANDY-STAGE"
          message: "${{ secrets.MESSAGE }}"
