on:
  push:
    tags: ["v*-stage"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mxdeployer-sample-stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet publish -r "win-x64" -c Release --self-contained true -p:PublishSingleFile=true -o ./build

      - name: Deploy to stage
        id: mxdeployer
        uses: mxdeployer/mxdeployer-action@v0.7.3
        with:
          az-service-bus-connection-string: "${{ secrets.AZSERVICEBUS }}"
          az-storage-connection-string: "${{ secrets.AZSTORAGE }}"
          source-path: ./build
          host: "WIN11ANDY-STAGE"
          app-name: "mxdeployer-sample"
          app-secrets: |
            {
              "message": "${{ secrets.MESSAGE }}"
            }

#      - name: Show me what you've got!
#        run: ls -laF ${{ steps.mxdeployer.outputs.archive-path }}
