on:
  push:
    tags: ["v*-prod"]

jobs:
  mxdeployer-stage-sample:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to production
        uses: mxdeployer/mxdeployer-action@v0.4
        with:
          dest-host: "WIN11ANDY-PROD"
          message: "${{ secrets.MESSAGE }}"
