on:
  push:
    tags: ["v*-stage"]

jobs:
  mxdeployer-sample-stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Deploy to stage
        uses: mxdeployer/mxdeployer-action@v0.4
        with:
          dest-host: "WIN11ANDY-STAGE"
          message: "${{ secrets.MESSAGE }}"
